// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPKmFhCDgGUioO8xorVpdBVqeimCA_Zao',
    appId: '1:282437708807:web:05150745fc9c93294e4ea2',
    messagingSenderId: '282437708807',
    projectId: 'disiplean-clone-92856',
    authDomain: 'disiplean-clone-92856.firebaseapp.com',
    databaseURL: 'https://disiplean-clone-92856-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'disiplean-clone-92856.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMYlMq_OT_r3F8xFlDaaFnpCMvhJcdbXw',
    appId: '1:282437708807:android:4a7525a76a0c18494e4ea2',
    messagingSenderId: '282437708807',
    projectId: 'disiplean-clone-92856',
    databaseURL: 'https://disiplean-clone-92856-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'disiplean-clone-92856.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH99gAEd-8zjoJCy46IRiBAa0sJXQc6cI',
    appId: '1:282437708807:ios:05af80e0974e64a74e4ea2',
    messagingSenderId: '282437708807',
    projectId: 'disiplean-clone-92856',
    databaseURL: 'https://disiplean-clone-92856-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'disiplean-clone-92856.appspot.com',
    iosBundleId: 'com.example.disipleanClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH99gAEd-8zjoJCy46IRiBAa0sJXQc6cI',
    appId: '1:282437708807:ios:0f8b88863893b0df4e4ea2',
    messagingSenderId: '282437708807',
    projectId: 'disiplean-clone-92856',
    databaseURL: 'https://disiplean-clone-92856-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'disiplean-clone-92856.appspot.com',
    iosBundleId: 'com.example.disipleanClone.RunnerTests',
  );
}
