// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZYK_sbcE9viK9ABrXbUoGCazhK_IF4mY',
    appId: '1:1096699310462:web:3f58cd5584116dc405832f',
    messagingSenderId: '1096699310462',
    projectId: 'disiplean-clone',
    authDomain: 'disiplean-clone.firebaseapp.com',
    storageBucket: 'disiplean-clone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvHTLYkgiWOkY0VM5-pAoKhUeHwum_Nk0',
    appId: '1:1096699310462:android:608c1bf67bd7e64e05832f',
    messagingSenderId: '1096699310462',
    projectId: 'disiplean-clone',
    storageBucket: 'disiplean-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2m2tD2c4CnkcgDYUMUr9kP4izxNmU-5I',
    appId: '1:1096699310462:ios:b7c93b33dfac84de05832f',
    messagingSenderId: '1096699310462',
    projectId: 'disiplean-clone',
    storageBucket: 'disiplean-clone.appspot.com',
    iosBundleId: 'com.example.disipleanClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2m2tD2c4CnkcgDYUMUr9kP4izxNmU-5I',
    appId: '1:1096699310462:ios:fde090ec8f954ec905832f',
    messagingSenderId: '1096699310462',
    projectId: 'disiplean-clone',
    storageBucket: 'disiplean-clone.appspot.com',
    iosBundleId: 'com.example.disipleanClone.RunnerTests',
  );
}
